# tap "romkatv/powerlevel10k"

brew "bat"
brew "coreutils"
brew "eza"
brew "gh"
brew "git"
brew "go"
brew "jq"
brew "neovim"
brew "node"
brew "nvm"
brew "starship"
brew "tree"
brew "vale"
brew "yarn"
brew "yt-dlp"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "brave-browser"
cask "discord"
cask "docker"
cask "figma"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "ghostty"
cask "karabiner-elements"
cask "keepingyouawake"
cask "nordvpn"
cask "postman"
cask "rectangle"
cask "raycast"
cask "signal"
cask "spotify"
cask "steam"
cask "telegram"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "workman"
cask "zoom"

# Shouldn't need this, log in with Work VScode account instead.
# vscode "bierner.markdown-preview-github-styles"
# vscode "bpruitt-goddard.mermaid-markdown-syntax-highlighting"
# vscode "bradlc.vscode-tailwindcss"
# vscode "catppuccin.catppuccin-vsc"
# vscode "chrischinchilla.vale-vscode"
# vscode "continue.continue"
# vscode "davidanson.vscode-markdownlint"
# vscode "dbaeumer.vscode-eslint"
# vscode "docker.docker"
# vscode "eamodio.gitlens"
# vscode "esbenp.prettier-vscode"
# vscode "figma.figma-vscode-extension"
# vscode "github.copilot"
# vscode "github.copilot-chat"
# vscode "github.github-vscode-theme"
# vscode "hashicorp.hcl"
# vscode "ilgoncalves.macchiato-theme"
# vscode "jock.svg"
# vscode "ms-azuretools.vscode-containers"
# vscode "ms-python.black-formatter"
# vscode "ms-python.debugpy"
# vscode "ms-python.python"
# vscode "ms-python.vscode-pylance"
# vscode "ms-python.vscode-python-envs"
# vscode "ms-vscode.makefile-tools"
# vscode "ms-vscode.vscode-speech"
# vscode "nhoizey.gremlins"
# vscode "nucllear.vscode-extension-auto-import"
# vscode "redhat.vscode-yaml"
# vscode "redocly.openapi-vs-code"
# vscode "shuworks.vscode-table-formatter"
# vscode "simonsiefke.svg-preview"
# vscode "tamasfe.even-better-toml"
# vscode "tuxtina.json2yaml"
# vscode "unifiedjs.vscode-mdx"
# vscode "vscodevim.vim"
# vscode "wmaurer.change-case"
# vscode "yzhang.markdown-all-in-one"
# vscode "zahidnazir.material-theme-twilight-wave"