"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

palette = 'arthur'

right_format = """
$battery
$time"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
truncation_length = 5
truncate_to_repo = true
truncation_symbol = ""
style = "sapphire"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "green"
format = '[$symbol $branch]($style)'

[git_status]
format = " ([$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed]($style))"
conflicted = "[◪](italic bright-magenta)"
ahead = "[▴${ahead_count}](green)"
behind = "[▿${behind_count}](red)"
diverged = "[▴${ahead_count}](green)[▿${behind_count}](red)"
untracked = "[◌](italic yellow)"
stashed = "[◃◈](sapphire)"
modified = "[●](yellow)"
staged = "[▪{$count}](peach)"
renamed = "[◎](blue)"
deleted = "[✕](red)"

# Catpuccin macchiato palette
[palettes.arthur]
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
